<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Website Example Image</name>
   <tag></tag>
   <elementGuidId>3b90f9f6-a925-453f-acd1-d52c8a773a42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='web-image-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;web-image-1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7c885cf3-ce78-49d3-a099-7631994c83a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>web-image-1</value>
      <webElementGuid>f98be059-1ee1-47f6-8d76-691d080f3391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>58cb2258-ede5-4054-bea8-02a5e384ab8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>e0498baf-121a-4373-8316-648bcda1cf00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>efd28906-cafe-40ab-8f65-7f7838853928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>b6281e5c-6938-4e42-9f3b-2c42e27bb7c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e26b363f-232f-490e-9781-c6f15ef2c2d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=%2FdogWeb.png&amp;w=640&amp;q=75 1x, /_next/image?url=%2FdogWeb.png&amp;w=1080&amp;q=75 2x</value>
      <webElementGuid>a3886e13-cb0b-4e4e-ba8b-2265e20022fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=%2FdogWeb.png&amp;w=1080&amp;q=75</value>
      <webElementGuid>e8bc2612-8316-47c5-8ca2-d857ffab7157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__className_20951f&quot;]/main[1]/main[@class=&quot;flex flex-col w-screen max-w-full bg-white&quot;]/section[@class=&quot;w-screen max-w-full min-h-screen py-0 sm:py-10 md:py-10 lg:py-10 xl:py-10 pb-10 bg-[#263a9d] flex items-center justify-center&quot;]/div[@class=&quot;flex flex-col items-center justify-center animate-slide-in-from-left&quot;]/div[@class=&quot;p-2 mt-10 bg-gray-500 bg-opacity-50 rounded-lg&quot;]/img[1]</value>
      <webElementGuid>b97759da-34a3-498b-8d66-fd68b2f18c64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='web-image-1']</value>
      <webElementGuid>4eabbc3c-7374-4a1f-a5fa-0900dd66a89a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>1a5f9014-637b-4a9f-83ec-043356e736eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'web-image-1' and @src = '/_next/image?url=%2FdogWeb.png&amp;w=1080&amp;q=75']</value>
      <webElementGuid>0efa3277-dbde-441f-86e1-d182d4cf3af3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
